/** UserCards public contract: authoritative private operations, queries, imports, recovery and compatible reference preparation (docs/user-cards.md). */

export { UserCardsError, type UserCardsFailureCode } from './internal/errors.js';
export type {
  UserCardsSqlExecutor,
  UserCardsSqlRow,
  UserCardsSqlTransactor,
  UserCardsSqlValue,
} from './internal/executor.js';
export {
  associationLevelsByTagKind,
  associationTargetLevels,
  copyConditions,
  importEntryStates,
  importSessionStates,
  tagKinds,
  userTagKinds,
  USERCARDS_LIMITS,
  type Association,
  type AssociationId,
  type AssociationTargetLevel,
  type CopyCondition,
  type CopyId,
  type ImportCandidate,
  type ImportDestination,
  type ImportEntry,
  type ImportEntryId,
  type ImportEntryState,
  type ImportOperationId,
  type ImportSession,
  type ImportSessionId,
  type ImportSessionState,
  type ImportSourceLine,
  type PhysicalCopy,
  type Tag,
  type TagId,
  type TagKind,
  type TrustedUserContext,
  type UserTagKind,
} from './internal/model.js';
export {
  type AttachImportCandidatesInput,
  type CaptureStageResult,
  type ConfirmImportEntryInput,
  type ConfirmImportInput,
  type DiscardImportEntryInput,
  type DiscardImportSessionInput,
  type ImportConfirmationResult,
  type ImportEntryChangeResult,
  type ImportEntryListResult,
  type ImportOperationRecoveryResult,
  type ImportOperations,
  type ImportReceipt,
  type ImportSessionChange,
  type ImportSessionListResult,
  type ImportSourceInput,
  type ImportStageResult,
  type ListImportEntriesOptions,
  type ListImportSessionsOptions,
  type ReviewImportEntryInput,
  type StageCaptureInput,
  type StageImportEntriesInput,
  type StageImportEntryInput,
} from './internal/import-service.js';
export {
  createMoxfieldDeckSource,
  type MoxfieldDeckSource,
  type MoxfieldSourceOptions,
} from './internal/moxfield.js';
export {
  createSourceImports,
  type MoxfieldDeckImport,
  type PastedCardListImport,
  type ReviewedWizardsLine,
  type SourceImportDependencies,
  type SourceImportOperations,
  type SourceImportOutcome,
  type SourceImportResult,
  type SourceImportRow,
  type StageSourceImportInput,
  type WizardsPreconImport,
} from './internal/source-imports.js';
export {
  type LoadMigrationPlanInput,
  type MigrationLoadResult,
  type MigrationOperations,
  type MigrationReadback,
} from './internal/migration-contract.js';
export {
  type MigrationPlan,
  type MigrationPlanAccount,
  type MigrationPlanState,
} from './internal/migration-plan.js';
export {
  USERCARDS_ACCOUNT_SCOPE_SQL,
  USERCARDS_ACCOUNT_SETTING,
  usercardsQueryGrants,
  usercardsSchemaSql,
} from './internal/schema.js';
export {
  USERCARDS_QUERY_LIMITS,
  userCardsOrderingFields,
  userCardsReferenceKey,
  userCardsResultLevels,
  userCardsSortDirections,
  type ReadUserCardsFragmentsInput,
  type UserCardsFragment,
  type UserCardsFragmentsResult,
  type UserCardsOrdering,
  type UserCardsOrderingField,
  type UserCardsPhysicalDetail,
  type UserCardsQuery,
  type UserCardsQueryCriterion,
  type UserCardsQueryEntry,
  type UserCardsQueryInput,
  type UserCardsQueryPage,
  type UserCardsQueryScope,
  type UserCardsReference,
  type UserCardsResultLevel,
  type UserCardsSortDirection,
} from './internal/query-model.js';
export { createUserCardsQueries, type UserCardsQueries } from './internal/queries.js';
export {
  createUserCardsReferencePreparation,
  type UserCardsReferencePreparation,
  type UserCardsReferencePreparationResult,
} from './internal/references.js';
export {
  createUserCards,
  type AssociationChangeResult,
  type AssociationListResult,
  type AssociationReadResult,
  type AssociationRemovalResult,
  type ChangeAssociationInput,
  type CopyChangeResult,
  type CopyLocationResult,
  type CopyReadResult,
  type CorrectCopyInput,
  type CreateAssociationInput,
  type CreateCopiesInput,
  type CreateTagInput,
  type ListAssociationsOptions,
  type RemoveAssociationInput,
  type RenameTagInput,
  type SetCopyLocationInput,
  type TagChangeResult,
  type TagListOptions,
  type TagListResult,
  type TagReadResult,
  type UserCards,
  type UserCardsDependencies,
} from './internal/service.js';
