/** UserInterface public contract: navigation, pages, card views, editors and capture controls (docs/ui/architecture.md). */

export { createBrowsePages } from './pages/index.js';
export { createCollectionPages } from './pages/index.js';
export { createImportPages } from './pages/index.js';
export { createOrganizationPages } from './pages/index.js';
export { createPages } from './pages/index.js';
export {
  createNavigation,
  createDialogs,
  createNoticeHost,
  createViewStateStore,
  readUiCatalogFinish,
  readUiCatalogLevel,
  readUiCollectionLevel,
  readUiView,
  uiCatalogFinishes,
  uiCatalogLevels,
  uiCollectionLevels,
  uiFinishLabel,
  uiHref,
  uiPageNames,
  uiViewTitle,
  UI_ROUTE_PREFIX,
  type Navigation,
  type NavigationOptions,
  type UiAccount,
  type UiCatalogLevel,
  type UiCollectionLevel,
  type UiDialogOptions,
  type UiDialogHost,
  type UiDialogs,
  type UiIdentity,
  type UiNotice,
  type UiNoticeHost,
  type UiNoticeAction,
  type UiNotices,
  type UiNoticeSeverity,
  type UiPageContext,
  type UiPageDefinition,
  type UiPageHandle,
  type UiPageName,
  type UiPageRegistry,
  type UiRetainedRelease,
  type UiView,
  type UiViewSnapshot,
  type UiViewStateStore,
} from './navigation/index.js';
export {
  createUserInterface,
  type UserInterface,
  type UserInterfaceOptions,
} from './internal/composition.js';
export type { CaptureControlsFactory, UiPresentationModules } from './shared/modules.js';
export { UI_LIMITS } from './shared/limits.js';
export { reportUiFailure } from './shared/notices.js';
export {
  createCaptureControls,
  type UiCaptureControls,
  type UiCaptureOptions,
} from './capture-controls/index.js';
export {
  cardListBasicContent,
  createCardListView,
  type UiActionIntent,
  type UiCardList,
  type UiCardListOptions,
  type UiCardListPresentation,
  type UiEntryImage,
  type UiEntryOwnership,
  type UiEntryTag,
  type UiListAction,
} from './card-views/index.js';
export {
  createCardViews,
  type CardViewDetail,
  type CardViewDetailOptions,
  type CardViewEntryPresentation,
  type CardViewOpenOptions,
  type CardViewPickerChoice,
  type CardViewPickerOptions,
  type CardViews,
} from './card-views/index.js';
export {
  copyChangeTool,
  correctCopy,
  createCopyAccess,
  uiCopyConditions,
  uiCopyReadNoticeId,
  type UiCopyAccess,
  type UiCopyChange,
  type UiCopyClient,
  type UiCopyCorrection,
  type UiCopyCorrectionOutcome,
  type UiCopyRead,
} from './editors/index.js';
export {
  addAssociation,
  addToTagTool,
  createTag,
  createTagAccess,
  moveCopyById,
  outcomeText,
  removeAssociation,
  renameTag,
  saveAssociation,
  uiAssociationLevelLabel,
  uiAssociationLevelsByTagKind,
  uiTagKindLabel,
  uiTagKinds,
  type AssociationCorrection,
  type AssociationRemoval,
  type UiChangeOutcome,
  type UiTagAccess,
  type UiTagClient,
  type UiTagKind,
} from './editors/index.js';
export {
  applyAction,
  beginSourceImport,
  confirmImport,
  createImportAccess,
  discardImportEntry,
  discardImportSession,
  recoverConfirmation,
  reopenSourceImport,
  retryRetainedAttempt,
  reviewImportEntry,
  stageImportLines,
  uiImportCandidates,
  uiImportIdentity,
  uiImportSourceLabel,
  type UiActionRequest,
  type UiImportAccess,
  type UiImportCandidate,
  type UiImportClient,
  type UiImportLine,
  type UiOperationAction,
  type UiOperationOutcome,
} from './editors/index.js';
export { createEditors, type Editors, type EditorsOptions } from './editors/index.js';
