/** CardList public contract: owner queries, independent fragments, bounded windows, selection and restoration (docs/card-list.md). */

export { CARD_LIST_LIMITS } from './internal/limits.js';
export { createCardList, groupCardListEntries } from './internal/list.js';
export { createRecentActivity, type CardListRecentActivity } from './internal/recent.js';
export {
  createCardListBrowser,
  type CardListAccountBindings,
  type CardListBrowser,
  type CardListBrowserOptions,
  type CardListRecentBinding,
} from './internal/browser.js';
export {
  pendingEntriesBinding,
  pendingEntryKey,
  pendingListEntry,
  type CardListPendingEntries,
  type CardListPendingEntriesRead,
  type CardListPendingRecord,
} from './internal/bindings/pending.js';
export {
  associationKey,
  associationListEntry,
  referenceOfAssociation,
  tagAssociationsBinding,
  type CardListTagAssociations,
  type CardListTagAssociationsRead,
} from './internal/bindings/associations.js';
export {
  catalogQueryRequest,
  catalogQuerySource,
  catalogEntryOf,
  cardListEntryKey,
  cardListTargetOfKey,
  collectionQueryRequest,
  collectionQuerySource,
  entryOwnershipReader,
  isInvalidatedContinuation,
  pickerQuerySource,
  readFailureCode,
  userCardsCounts,
  type CardListCountsAccess,
  type CardListEntryCounts,
  type CardListUserCardsRead,
  type CardListResultLevel,
  type CardListCatalogQuery,
  type CardListCollectionQuery,
  type CardListPickerQuery,
} from './internal/bindings/query.js';
export {
  cardPrintingsSource,
  printingEntry,
  printingIdOfEntryKey,
  printingImagesReader,
  resolveCards,
  resolvePrintings,
} from './internal/bindings/catalog.js';
export {
  detailTargetSource,
  type CardListDetailBindingOptions,
  type CardListDetailCopyReader,
  type CardListDetailTarget,
} from './internal/bindings/detail.js';
export { usercardsChanges, type CardListUserCardsChanges } from './internal/bindings/usercards.js';
export {
  cardListFragmentKinds,
  type CardList,
  type CardListChange,
  type CardListChangeSource,
  type CardListEntry,
  type CardListEntryAbsence,
  type CardListEntryBasic,
  type CardListEntryCard,
  type CardListEntryDetail,
  type CardListEntryImage,
  type CardListEntryOwnership,
  type CardListEntryPrinting,
  type CardListEntryQuantity,
  type CardListEntrySnapshot,
  type CardListEntryTag,
  type CardListFocus,
  type CardListFragmentKind,
  type CardListFragmentReader,
  type CardListFragmentReaders,
  type CardListFragmentRequest,
  type CardListFragmentResult,
  type CardListFragmentState,
  type CardListSettledFragmentState,
  type CardListGroup,
  type CardListOptions,
  type CardListPage,
  type CardListPosition,
  type CardListPositionReport,
  type CardListRead,
  type CardListRestoration,
  type CardListRetained,
  type CardListSelectedTarget,
  type CardListSelection,
  type CardListSnapshot,
  type CardListSource,
  type CardListSourceRequest,
  type CardListTarget,
  type CardListTool,
  type CardListToolSelection,
  type CardListToolState,
  type CardListViewportDemand,
} from './internal/contract.js';
